sudo: required
services:
 - docker

before_install:
 - docker build -t testrectdock -f ./client/Dockerfile.dev ./client

script:
 - docker run darekb89/testrectdock npm test -- --coverage
 - docker run -e CI=true darekb89/testrectdock npm test

after_success:
 - docker build -t darekb89/multi-client ./client
 - docker build -t darekb89/multi-nginx ./nginx
 - docker build -t darekb89/multi-server ./server
 - docker build -t darekb89/multi-worker ./worker
#  logg to docker cli
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push darekb89/multi-client
 - docker push darekb89/multi-nginx 
 - docker push darekb89/multi-server
 - docker push darekb89/multi-worker